import Head from 'next/head'
import Layout from '../../components/common/Layout';
import ListingsTable from '../../components/Listings/ListingsTable'; 

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout title="Listings">
            <ListingsTable/>
        </Layout>
      </main>
    </>
  );
}